services:
  - type: web
    name: dairy-app
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn milkapp_project.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: milkapp_project.settings
      - key: PYTHON_VERSION
        value: 3.11
